### ISSUE TITLE
Static/Generic/fluent way to get toggle value?

### ISSUE THREAD

**Issue by jason-roberts** [jason-roberts/FeatureToggle#72]
For example Is.Feature<MyAwesomeFeatureToggle>().Enabled

**Comment by jason-roberts** [comment]
A fluent/readable style might require the naming of derived feature toggle classes to follow some pattern

**Comment by vermeeca** [comment]
Re: this issue and #106, what about an implementation like the following?

https://github.com/jason-roberts/FeatureToggle/compare/master...vermeeca:GenericFactory

Would love feedback there.  If it looks OK, I'll submit a PR

**Comment by jason-roberts** [comment]
Thanks @vermeeca :) - hold off on the PR for the moment, would like to think this through a bit more. In your example, what do you see as the benefit of the caching?

**Comment by vermeeca** [comment]
Initially I was thinking for performance reasons, but I think it keeps more in line with the rest of the library not to worry about that.

If creating particular toggles is expensive, one could always use the Feature factory, inject all of the IFeatureToggles into it with a container, and then control the lifecycle of that factory in order to optimize.

Updated the branch to reflect that.

https://github.com/jason-roberts/FeatureToggle/compare/master...vermeeca:GenericFactory

**Comment by jason-roberts** [comment]
Implemented in v3.4
